import { FileSearch } from "lucide-react";
import SectionLabel from "../common/SectionLabel";

export default function EvidenceCard({ text }) {
  return (
    <div className="rounded-lg border border-ink-3 bg-ink-2 p-4">
      <SectionLabel icon={FileSearch} tone="ink">
        📄 Retrieved Evidence
      </SectionLabel>
      <blockquote className="mt-2.5 border-l-2 border-brass pl-3 font-mono text-[12.5px] leading-relaxed text-text-onink-muted">
        {text}
      </blockquote>
      <p className="mt-2 text-[11px] text-text-onink-muted/80">
        Verbatim text from the original document — not generated by AI.
      </p>
    </div>
  );
}
